// logo1.h
#pragma once

// this file is autogenerated - see tga_tools.pl

#include "../palettetools.h"

extern bool do_update_logo1;
extern bool do_update_menu1;
extern bool do_update_menu2;
extern bool do_update_menu3;
extern bool do_update_menu4;
extern bool update_palette_logo1;
extern bool update_palette_menu1;
extern bool update_palette_menu2;
extern bool update_palette_menu3;
extern bool update_palette_menu4;

// tracks the accumulation of changes for the HSL color model
extern GlobalHSL hsl_incSprites;

// initial image setup: hue, saturation, luminance, x_pos, y_pos, x_scale, y_scale, x_scroll (rate), y_scroll (rate), min_sat_id, max_sat_id, min_lum_id, max_lum_id

extern ImageAttr attrSprites;

extern PaletteRange p_rangeLogo;
extern PaletteRange p_rangeMenu1;
extern PaletteRange p_rangeMenu2;
extern PaletteRange p_rangeMenu3;
extern PaletteRange p_rangeMenu4;

void init_sprites_img(void);

bool update_sprites_color(PaletteRange *range);

bool update_sprites_palette(PaletteRange *range);

void reset_sprites (void);