// bg0.h
#ifndef BG0_H
#define BG0_H

// this file is autogenerated - see tga_tools.pl

#include "../palettetools.h"
#include "../lighting.h"

// palette for normal map calculations
RgbPalette rgbBg0 = {
    { {255, 203, 87}, {255, 113, 81}, {255, 165, 115}, {251, 31, 71}, {163, 191, 239}, {211, 217, 219}, {255, 237, 204}, {255, 255, 241}, 
      {33, 77, 65}, {61, 95, 71}, {237, 205, 159}, {199, 177, 115}, {135, 137, 73}, {91, 121, 65}, {153, 151, 99}, {255, 255, 241} }
};

// buffer palette for writing to CRAM (populated at runtime)
RgbBuff bufferBg0 = {
    { 0, 0, 0, 0, 0, 0, 0, 0, 
      0, 0, 0, 0, 0, 0, 0, 0 }
};

// palette for calculating color and lighting - hue, saturation, luminance (populated at runtime)
HslPalette hslBg0 = {
    { {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, 
      {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0}, {0, 0, 0} }
};

// palette ranges - used with the palette group collection.
PaletteRange p_rangeBg0 = { 0, 15 };

// tracks the accumulation of changes for the HSL color model
GlobalHSL hsl_incBg0 = {0, 0, 0};

// initial image setup: hue, saturation, luminance, x_pos, y_pos, x_scale, y_scale, x_scroll (rate), y_scroll (rate), min_sat_id, max_sat_id, min_lum_id, max_lum_id
ImageAttr attrBg00 = { 0, 0, 0, toFIXED(0.0), toFIXED(0.0), toFIXED(0.0), toFIXED(0.0), 0, 0, 0, 0}; // default attributes (for single color image)

PaletteRange *paletteRangeBg0[] = {
    &p_rangeBg0   // Index 0
};

Uint8 paletteGroups = 1;

Uint8 bg0_spr_id;

static jo_palette bg0_palette;

// Helper Functions

jo_palette	*my_bg0_palette_handling(void)
{
    jo_create_palette(&bg0_palette);
    return (&bg0_palette);
}

void init_bg0_img(void) {
    jo_img_8bits    img;
    jo_set_tga_palette_handling(my_bg0_palette_handling);
    img.data = JO_NULL;
    jo_tga_8bits_loader(&img, JO_ROOT_DIR, "BG0.TGA", 0);
    jo_vdp2_set_nbg1_8bits_image(&img, bg0_palette.id, false);
    jo_free_img(&img);

    MultiRgbToHsl(&hslBg0, &rgbBg0, &p_rangeBg0);
    min_max_sl_id(&hslBg0, &p_rangeBg0, &attrBg00);
}

void update_bg0_color(void) {
    MultiPalette2Buffer(&bufferBg0, &hslBg0, &hsl_incBg00, &p_rangeBg0);
}

void update_bg0_palette(void) {
    UpdatePaletteFromBuffer(&bufferBg0, &bg0_palette, &p_rangeBg0);
}

void reset_bg0 (void) {
    MultiRgbToHsl(&hslBg0, &rgbBg0, &p_rangeBg0);
    min_max_sl_id(&hslBg0, &p_rangeBg0, &attrBg00);
    MultiPalette2Buffer(&bufferBg0, &hslBg0, &hsl_incBg00, &p_rangeBg0);
}

#endif // BG0_H
