// sprite_colors.h
#pragma once

// this file is autogenerated - see tga_tools.pl

#include "../main.h"
#include "../palettetools.h"

extern bool do_update_ppplogo;
extern bool do_update_logo1;
extern bool do_update_Pmenu[MAX_PLAYERS];
extern bool do_update_PmenuAll;
extern bool do_update_menu1;
extern bool do_update_menu2;
extern bool do_update_menu3;
extern bool do_update_menu4;
extern bool do_update_fish;
extern bool do_update_bomb;
extern bool do_update_shroom;
extern bool update_palette_ppplogo;
extern bool update_palette_logo1;
extern bool update_palette_Pmenu[MAX_PLAYERS];
extern bool update_palette_PmenuAll;
extern bool update_palette_menu1;
extern bool update_palette_menu2;
extern bool update_palette_menu3;
extern bool update_palette_menu4;
extern bool update_palette_fish;
extern bool update_palette_bomb;
extern bool update_palette_shroom;

// tracks the accumulation of changes for the HSL color model
extern GlobalHSL hsl_incSprites;

extern HslPalette hslSprites;

extern ImageAttr attrSprites;

extern PaletteRange p_rangeLogo;
extern PaletteRange p_rangePmenu[MAX_PLAYERS];
extern PaletteRange p_rangePmenuAll;
extern PaletteRange p_rangePmenu4;
extern PaletteRange p_rangeMenu1;
extern PaletteRange p_rangeMenu2;
extern PaletteRange p_rangeMenu3;
extern PaletteRange p_rangeMenu4;
extern PaletteRange p_rangeFish;
extern PaletteRange p_rangeBomb;
extern PaletteRange p_rangeShroom;
extern PaletteRange p_rangeNormalMap;

void init_sprites_img(void);

bool calculate_sprites_color(PaletteRange *range);

bool update_sprites_color(PaletteRange *range);

bool update_sprites_palette(PaletteRange *range);

void reset_sprites(void);

// HSL calc
void update_ppplogo_color(void);
void update_ppplogo_palette(void);

// title screen menu
static inline void updateTitleMenuColors(void) {
	if (do_update_menu1) {
		update_palette_menu1 = update_sprites_color(&p_rangeMenu1);
		do_update_menu1 = false;
	}
	if (do_update_menu2) {
		update_palette_menu2 = update_sprites_color(&p_rangeMenu2);
		do_update_menu2 = false;
	}
	if (do_update_menu3) {
		update_palette_menu3 = update_sprites_color(&p_rangeMenu3);
		do_update_menu3 = false;
	}
	if (do_update_menu4) {
		update_palette_menu4 = update_sprites_color(&p_rangeMenu4);
		do_update_menu4 = false;
	}
}
static inline void updateTitleMenuPalette(void) {
	if (update_palette_menu1) {
		update_palette_menu1 = update_sprites_palette(&p_rangeMenu1);
	}
	if (update_palette_menu2) {
		update_palette_menu2 = update_sprites_palette(&p_rangeMenu2);
	}
	if (update_palette_menu3) {
		update_palette_menu3 = update_sprites_palette(&p_rangeMenu3);
	}
	if (update_palette_menu4) {
		update_palette_menu4 = update_sprites_palette(&p_rangeMenu4);
	}
}

// team select menu
static inline void updateTeamSelectColors(void) {
	if (do_update_PmenuAll) {
		update_palette_PmenuAll = update_sprites_color(&p_rangePmenuAll);
		do_update_PmenuAll = false;
	}
}
static inline void updateTeamSelectPalette(void) {
	if (update_palette_PmenuAll) {
		update_palette_PmenuAll = update_sprites_palette(&p_rangePmenuAll);
	}
}

// gameplay
static inline void updateGameColors(void) {
	if (do_update_shroom) {
		update_palette_shroom = update_sprites_color(&p_rangeShroom);
		do_update_shroom = false;
	}
	Uint8 i = 0;
	if (do_update_Pmenu[i]) {
		update_palette_Pmenu[i] = update_sprites_color(&p_rangePmenu[i]);
		do_update_Pmenu[i] = false;
	}
	i++;
	if (do_update_Pmenu[i]) {
		update_palette_Pmenu[i] = update_sprites_color(&p_rangePmenu[i]);
		do_update_Pmenu[i] = false;
	}
	i++;
	if (do_update_Pmenu[i]) {
		update_palette_Pmenu[i] = update_sprites_color(&p_rangePmenu[i]);
		do_update_Pmenu[i] = false;
	}
	i++;
	if (do_update_Pmenu[i]) {
		update_palette_Pmenu[i] = update_sprites_color(&p_rangePmenu[i]);
		do_update_Pmenu[i] = false;
	}
	if (do_update_PmenuAll) {
		update_palette_PmenuAll = update_sprites_color(&p_rangePmenuAll);
		do_update_PmenuAll = false;
	}
}
static inline void updateGamePalette(void) {
	if (update_palette_shroom) {
		update_palette_shroom = update_sprites_palette(&p_rangeShroom);
	}
	Uint8 i = 0;
	if (update_palette_Pmenu[i]) {
		update_palette_Pmenu[i] = update_sprites_palette(&p_rangePmenu[i]);
	}
	i++;
	if (update_palette_Pmenu[i]) {
		update_palette_Pmenu[i] = update_sprites_palette(&p_rangePmenu[i]);
	}
	i++;
	if (update_palette_Pmenu[i]) {
		update_palette_Pmenu[i] = update_sprites_palette(&p_rangePmenu[i]);
	}
	i++;
	if (update_palette_Pmenu[i]) {
		update_palette_Pmenu[i] = update_sprites_palette(&p_rangePmenu[i]);
	}
	if (update_palette_PmenuAll) {
		update_palette_PmenuAll = update_sprites_palette(&p_rangePmenuAll);
	}
}